"""same shit

Revision ID: 7d90e8b5b80e
Revises: 001
Create Date: 2026-03-04 05:40:35.910059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7d90e8b5b80e'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkplans_copy')
    op.add_column('user', sa.Column('profile_bg_url', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_bg_url')
    op.create_table('checkplans_copy',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_src', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_alt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('days', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('days_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('initial_likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_plan_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filter_tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region_tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('traveler_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('season_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
