-- Перенос чек-планов из personal-check-plans.js в таблицу checkplans
-- author_id = 4, статика: https://setly.space/storage/check-plans/<filename>
-- Выполнять при необходимости: psql -d your_db -f backend/database/seed_check_plans.sql

INSERT INTO checkplans (
  id_str,
  author_id,
  image_src,
  image_alt,
  days,
  days_num,
  location,
  title,
  description,
  visibility,
  initial_likes,
  check_plan_data_id,
  filter_tag,
  region_tag,
  traveler_tags,
  season_tags
) VALUES
  (
    'setly-japan-2025',
    4,
    'https://setly.space/storage/check-plans/city-1.png',
    'Япония',
    '10 дней',
    10,
    'Киото',
    'Япония 2025',
    'Список для тех, кто как я любит много ходить и искать не туристические места',
    'public',
    0,
    0,
    'По городам',
    'Азия',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-mountains-1',
    4,
    'https://setly.space/storage/check-plans/mountains-1.png',
    'Горы',
    '7 дней',
    7,
    'Алтай',
    'Треккинг на Алтае',
    'Без гида, ночёвки в палатке. Взяла минимум вещей, не пожалела ни о чём)',
    'public',
    0,
    0,
    'В горы',
    'Россия и СНГ',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-mountains-2',
    4,
    'https://setly.space/storage/check-plans/mountains-2.png',
    'Горы',
    '5 дней',
    5,
    'Эльбрус',
    'Эльбрус до Приюта 11',
    'Для тех, кто хочет почувствовать горы, но не рисковать',
    'public',
    0,
    0,
    'В горы',
    'Россия и СНГ',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-mountains-3',
    4,
    'https://setly.space/storage/check-plans/mountains-3.png',
    'Горы',
    '3 дня',
    3,
    'Кавказ',
    'Покоряя горы Кавказа',
    'Смесь треккинга, местных гестхаусов и горячих источников',
    'public',
    0,
    0,
    'В горы',
    'Кавказ',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-city-2',
    4,
    'https://setly.space/storage/check-plans/city-2.png',
    'Город',
    '5 дней',
    5,
    'Токио',
    'Токио без спешки',
    'Не пытался увидеть всё, выбрал 3 района, ходил пешком, пил кофе в тихих киосках',
    'public',
    0,
    0,
    'По городам',
    'Азия',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-city-3',
    4,
    'https://setly.space/storage/check-plans/city-3.png',
    'Город',
    '7 дней',
    7,
    'Киото',
    'Южная Корея 2025',
    'Городской марафон без природы — музеи, уличная еда, ночные рынки и корейская косметика',
    'public',
    0,
    0,
    'По городам',
    'Азия',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-beach-1',
    4,
    'https://setly.space/storage/check-plans/beach-1.png',
    'Пляж',
    '10 дней',
    10,
    'Паттайя',
    'Чилловый Тайланд',
    'Ходила по храмам, купалась в море и грелась на солнце без экскурсий в 7 утра',
    'public',
    0,
    0,
    'На пляж',
    'Азия',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-beach-2',
    4,
    'https://setly.space/storage/check-plans/beach-2.png',
    'Пляж',
    '14 дней',
    14,
    'Куала-Лумпур',
    'Малайзия',
    'Долгая поездка с пересадками между городом, джунглями и пляжем',
    'public',
    0,
    0,
    'На пляж',
    'Азия',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-beach-3',
    4,
    'https://setly.space/storage/check-plans/beach-3.png',
    'Пляж',
    '7 дней',
    7,
    'Афины',
    'Греция',
    'Мой самый лучший отдых и давняя мечта',
    'public',
    0,
    0,
    'На пляж',
    'Европа',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-family-1',
    4,
    'https://setly.space/storage/check-plans/family-1.png',
    'Семья',
    '7 дней',
    7,
    'Пхукет',
    'Пхукет с ребёнком',
    'Делюсь как путешествовать с детьми и не сойти с ума)',
    'public',
    0,
    0,
    'С семьёй или детьми',
    'Азия',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-family-2',
    4,
    'https://setly.space/storage/check-plans/family-2.png',
    'Семья',
    '5 дней',
    5,
    'Москва',
    'Москва + дети',
    'Парки, музеи, кафе с детскими меню. Главное бронировать онлайн!',
    'public',
    0,
    0,
    'С семьёй или детьми',
    'Россия и СНГ',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-family-3',
    4,
    'https://setly.space/storage/check-plans/family-3.png',
    'Семья',
    '10 дней',
    10,
    'Турция',
    'Семейный отдых',
    'Как ничего не забыть с двумя маленькими детьми',
    'public',
    0,
    0,
    'С семьёй или детьми',
    'Ближнее Зарубежье (Турция, Египет, ОАЭ)',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-long-1',
    4,
    'https://setly.space/storage/check-plans/long-1.png',
    'Долго',
    '14 дней',
    14,
    'Несколько стран',
    'Европа за месяц',
    '10+ городов, 4 страны, 30 дней. Как я составила модульную систему планов',
    'public',
    0,
    0,
    'Долго / Кочёвка',
    'Европа',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-long-2',
    4,
    'https://setly.space/storage/check-plans/long-2.png',
    'Долго',
    '21 день',
    21,
    'Несколько стран',
    'Юго-Восточная Азия',
    'Долгая поездка с пересадками между городом, джунглями и пляжем',
    'public',
    0,
    0,
    'Долго / Кочёвка',
    'Европа',
    '[]'::json,
    '[]'::json
  ),
  (
    'setly-long-3',
    4,
    'https://setly.space/storage/check-plans/long-3.png',
    'Долго',
    '10 дней',
    10,
    'Куала-Лумпур',
    'Малайзия',
    'Долгая поездка с пересадками между городом, джунглями и пляжем',
    'public',
    0,
    0,
    'Долго / Кочёвка',
    'Азия',
    '[]'::json,
    '[]'::json
  )
ON CONFLICT (id_str) DO NOTHING;

-- Связь пользователя 4 с чек-планами (для /me/checkplans)
INSERT INTO usercheckplan (user_id, id_str)
SELECT 4, id_str FROM unnest(ARRAY[
  'setly-japan-2025', 'setly-mountains-1', 'setly-mountains-2', 'setly-mountains-3',
  'setly-city-2', 'setly-city-3', 'setly-beach-1', 'setly-beach-2', 'setly-beach-3',
  'setly-family-1', 'setly-family-2', 'setly-family-3', 'setly-long-1', 'setly-long-2', 'setly-long-3'
]) AS t(id_str)
ON CONFLICT DO NOTHING;
